### PR TITLE
Add Gulp watch tasks

### PR DESCRIPTION
**Pull request by iamakulov**
Following https://github.com/zalmoxisus/redux-devtools-extension/pull/55.

Looking forward to your comments.

### CODE REVIEW

**Comment by zalmoxisus** [comment]
Heh, seems that the default task's line in gulpfile got too long now and it breaks ESLint :)

**Comment by iamakulov** [comment]
Whoops, my fault :) Will fix it once I get to the computer.

**Comment by iamakulov** [comment]
Or nope, wait, AFAIK I can edit it right from GitHub...

**Comment by iamakulov** [comment]
Let’s try this...

**Comment by iamakulov** [comment]
Looks like the tests are green now!

**Comment by zalmoxisus** [comment]
Thanks a lot :)

**Pull request merged**
